import streamlit as st
import requests
st.set_page_config(page_title="Professional Movie Recommender", layout="wide")

API_URL = "http://127.0.0.1:8000/recommend/"

st.title("🎬 Professional Movie Recommendation System")
st.write("Powered directly by TMDB! Tell us a movie, and we'll instantly search TMDB to give you recommendations.")

movie_name = st.text_input(
    "Enter any movie name you enjoyed:", 
    placeholder="e.g. Inception, The Matrix, Interstellar..."
)

count = st.number_input(
    "How many recommendations would you like to see?", 
    min_value=1, 
    max_value=20, 
    value=10,
    step=1
)
if st.button("Show me Recommendations"):
    if movie_name.strip() == "":
        st.warning("Please enter a movie name first! 😊")
    else:
        with st.spinner("Searching TMDB professionally..."):
            try:
                response = requests.get(
                    API_URL, 
                    params={"movie_title": movie_name, "count": count}
                )
                if response.status_code == 200:
                    data = response.json()
                    exact_movie_found = data.get("movie", movie_name)
                    recommendations = data.get("recommendations", [])
                    engine_used = data.get("engine_used", "Unknown Engine")
                    
                    if not recommendations:
                        st.info(f"We found '{exact_movie_found}', but no recommendations are available right now.")
                    else:
                        st.success(f"Success! Showing {len(recommendations)} recommendations for **{exact_movie_found}**")
                        st.caption(f"🧠 Recommendations generated by: **{engine_used}**")
                        
                        cols_per_row = 5
                        for i in range(0, len(recommendations), cols_per_row):
                            cols = st.columns(cols_per_row)
                            chunk = recommendations[i:i + cols_per_row]
                            for idx, movie in enumerate(chunk):
                                with cols[idx]:
                                    st.image(movie["poster_url"], use_container_width=True)
                                    st.write(f"**{movie['title']}**")
                elif response.status_code == 404:
                    st.error(f"Oops! TMDB couldn't find a movie matching '{movie_name}'. Try checking the spelling.")
                
                else:
                    st.error("Something went wrong on the server side.")
                    
            except requests.exceptions.ConnectionError:
                st.error("🚨 Connection Error: We couldn't connect to the API. Make sure your FastAPI is running!")